### ISSUE TITLE
Error due to semicolon in file name

### ISSUE THREAD

**Issue by zreitz** [zreitz/multismash#10]
Hi zreitz, I am having another problem with the tabulation that maybe you can help with. The antismash error that causing the tabulation to fail is different from the previous one above. I have included the portion of the snakemate log with the antismash error. It appears the genome sequence is corrupted in some way, which fails the antismash run... which then causes the tabulation to fail.

[multismash_error.txt](https://github.com/zreitz/multismash/files/13772763/multismash_error.txt)

_Originally posted by @alpole23 in https://github.com/zreitz/multismash/issues/9#issuecomment-1869664271_

**Comment by zreitz** [comment]
@alpole23 can you please confirm this worked?

**Comment by alpole23** [comment]
It appears to be working now! Thank you.

**Comment by zreitz** [comment]
Great, thanks for checking!
