### ISSUE TITLE
multismash/snakemake file storage space

### ISSUE THREAD

**Issue by alpole23** [zreitz/multismash#13]
Hi zreitz,

I was wondering if you have ever encountered the following issue regarding disc space when running multismash? This is with a run of about 5000 genomes. I realize this may be a snakemake issue and not a multismash issue, but I was hoping you may have some suggestions or can direct me to a reputable resource...

Error: 
> Shigella_sonnei_sh11sh241	OSError: [Errno 28] No space left on device: '/home/a-m/alexp2/antismash_results/antismash6/directory_410-411-412/antismash/Shigella_sonnei_sh11sh241/Shigella_sonnei_sh11sh241.json'
handle, "w")  # pylint: disable=consider-using-with
Shigella_sonnei_Shigella_sonnei_biotype_G_137	OSError: [Errno 28] No space left on device: '/home/a-m/alexp2/antismash_results/antismash6/directory_410-411-412/antismash/Shigella_sonnei_Shigella_sonnei_biotype_G_137/Shigella_sonnei_Shigella_sonnei_biotype_G_137.json'
ne 444, in copy2
Yersinia_pestis_YN2585	copyfile(src, dst, follow_symlinks=follow_symlinks)
Yersinia_pestis_YN2585	File "/home/a-m/alexp2/.conda/envs/antismash6/lib/python3.9/shutil.py", line 266, in copyfile
Yersinia_pestis_YN2585	with open(dst, 'wb') as fdst:
Yersinia_pestis_YN2585	OSError: [Errno 28] No space left on device: '/home/a-m/alexp2/antismash_results/antismash6/directory_410-411-412/antismash/Yersinia_pestis_YN2585/css/bacteria.css'
1-412/antismash/Yersinia_pestis_YN2619, /home/a-m/alexp2/antismash_results/antismash6/directory_410-411-412/antismash/Yersinia_pestis_YN2619/Yersinia_pestis_YN2619.gbk
    log: /home/a-m/alexp2/antismash_results/antismash6/directory_410-411-412/log/2023-12-28_23-44-21/antismash/Yersinia_pestis_YN2619.log (check log file(s) for error details)
    shell:
      
Some more details: I am running multismash on HPC cluster using SLURM and am allocating 2 nodes and 24 cores for the job, and I have plenty of storage space (510TB). However, this error happens when I try to run multismash with anything greater than 12 cores. This also occurs when I run more than one multismash snakemake config file at the same time even with just two jobs at 3 cores requested. My SLURM admin suggested I make a scratch temp folder that stores temp files for each job individually, so that was done, but did not fix the issue.

I don't understand how I can run my job at 12 cores with no issue, but anything greater is a no-go.

Thanks for your time and Happy New Year.

**Comment by alpole23** [comment]
I figured out what was happening. It was an issue with metadata storage.

**Comment by zreitz** [comment]
Happy New Year! I'm glad you figured it out (because I had no clue)
