### ISSUE TITLE
Extension of input files

### ISSUE THREAD

**Issue by rubmc97** [zreitz/multismash#16]
I was wondering if .gbff is the only extension format that works for the input for multiSMASH.
Already tried with gff and gff3 and it didn't work.

Thanks!

**Comment by zreitz** [comment]
GFF3 files alone are not suitable inputs for antiSMASH, but I've just added support for [paired fasta/GFF3 files](https://github.com/zreitz/multismash?tab=readme-ov-file#gff3-gene-annotations). Please let me know if this works out for you.
