### ISSUE TITLE
How to configure config file for antismash folders?

### ISSUE THREAD

**Issue by tarunaaggarwal** [zreitz/multismash#2]
Hi @zreitz,

I'm looking for guidance on how to configure the `config.yaml` file if I already have a set of antismash folders for several MAGs. I installed `antismash7` AND `snakemake` using `mamba` under the same env called `antismash7`. Below are my questions.

1. Before I run the `snakemake` commands, should I/can I activate my `antismash7` env which was installed using `mamba` as I normally would by running `mamba activate antismash7`?

2. I have a couple of questions about the `config.yaml` file. I put them in `?????` and my entire `config.yaml` file is attached. 

[config.txt](https://github.com/zreitz/multismash/files/12450218/config.txt)

Please let me know if you have any questions about my questions. Thank you for your help!

Taruna

**Comment by zreitz** [comment]
Hi Taruna,

Thanks for trying this out.

If antiSMASH and snakemake are installed in the same conda environment, then you should be able to run the workflow by excluding the `--use-conda` flag:
`snakemake --cores 1 --configfile config/config.yaml` 
Without `--use-conda`, the workflow will ignore the value of `antismash_conda`. Please let me know if that works (perhaps with the default `config.yaml` running on the `example/` files), and I'll update the readme.

---

```
# Parent directory for the input data, which can be genomes or antismash folders
?????? So this will be a collection of antismash folder, right? ??????
data_dir:
```
Yep, if your directory looks like this:
```
├── antismash_results
│   ├── genome_1
|   │   ├── genome_1.json
|   │   ├── genome_1.gbk
|   │   └── ...
│   ├── genome_2
|   │   ├── genome_2.json
|   │   ├── genome_2.gbk
|   │   └── ...
│   ├── ...
```
Then use `data_dir: antismash_results`

---
?????? Should I comment these out since I already antismash? ??????
antismash_command: "antismash" # or maybe `python /path/to/run_antismash.py`

You can ignore these if you're supplying antiSMASH results. They'll only be checked if the user supplies genomes.

Hope that clears everything up!

**Comment by tarunaaggarwal** [comment]
Hi @zreitz - Thank you for those suggestions! So I have been able to run everything successfully until BiG-SCAPE, and I think the issue now has to do with the calling BiG-SCAPE when excluding the `--use-conda`. Does `--use-conda` apply to all `conda` installed programs in the snakemake workflow? If so, is there a way to specify `conda` exclusions for specific tools?  I ask because in order to run BiG-SCAPE, I have to activate it first using `conda activate`. 

Below are the snakemake command I used and the log file in case it helps you. I also attached the config file for this run. 

command:

```
snakemake --cores 4 --configfile config/config_sarg.yaml 
```
Error: 

```
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 4
Rules claiming more threads will be scaled down.
Conda environments: ignored
Job stats:
job                 count
----------------  -------
all                     1
count_regions           1
run_bigscape            1
tabulate_regions        1
tar_bigscape            1
total                   5

Select jobs to execute...

[Tue Aug 29 02:33:25 2023]
rule count_regions:
    input: /home/taruna/sargassum/metagenomes/clean_data/antismash7-results/test/OAOBOCplusUnpairedReads.104, /home/taruna/sargassum/metagenomes/clean_data/antismash7-results/test/OAOBOCplusUnpairedReads.110
    output: /home/taruna/sargassum/metagenomes/clean_data/multismash-results/testingMultismash/testing-w-2-SargMAGs/region_counts.tsv
    jobid: 2
    reason: Missing output files: /home/taruna/sargassum/metagenomes/clean_data/multismash-results/testingMultismash/testing-w-2-SargMAGs/region_counts.tsv
    resources: tmpdir=/tmp


[Tue Aug 29 02:33:25 2023]
rule tabulate_regions:
    input: /home/taruna/sargassum/metagenomes/clean_data/antismash7-results/test/OAOBOCplusUnpairedReads.104, /home/taruna/sargassum/metagenomes/clean_data/antismash7-results/test/OAOBOCplusUnpairedReads.110
    output: /home/taruna/sargassum/metagenomes/clean_data/multismash-results/testingMultismash/testing-w-2-SargMAGs/all_regions.tsv
    jobid: 1
    reason: Missing output files: /home/taruna/sargassum/metagenomes/clean_data/multismash-results/testingMultismash/testing-w-2-SargMAGs/all_regions.tsv
    resources: tmpdir=/tmp


[Tue Aug 29 02:33:25 2023]
rule run_bigscape:
    input: /home/taruna/sargassum/metagenomes/clean_data/antismash7-results/test/OAOBOCplusUnpairedReads.104, /home/taruna/sargassum/metagenomes/clean_data/antismash7-results/test/OAOBOCplusUnpairedReads.110
    output: /home/taruna/sargassum/metagenomes/clean_data/multismash-results/testingMultismash/testing-w-2-SargMAGs/bigscape/index.html
    jobid: 4
    reason: Missing output files: /home/taruna/sargassum/metagenomes/clean_data/multismash-results/testingMultismash/testing-w-2-SargMAGs/bigscape/index.html
    resources: tmpdir=/tmp

[Tue Aug 29 02:33:27 2023]
Finished job 1.
1 of 5 steps (20%) done
[Tue Aug 29 02:33:27 2023]
Finished job 2.
2 of 5 steps (40%) done
[Tue Aug 29 02:33:28 2023]
Error in rule run_bigscape:
    jobid: 4
    input: /home/taruna/sargassum/metagenomes/clean_data/antismash7-results/test/OAOBOCplusUnpairedReads.104, /home/taruna/sargassum/metagenomes/clean_data/antismash7-results/test/OAOBOCplusUnpairedReads.110
    output: /home/taruna/sargassum/metagenomes/clean_data/multismash-results/testingMultismash/testing-w-2-SargMAGs/bigscape/index.html
    conda-env: bigscape
    shell:
        python /home/taruna/pkgs/BiG-SCAPE-1.1.5/bigscape.py -i /home/taruna/sargassum/metagenomes/clean_data/antismash7-results/test -o /home/taruna/sargassum/metagenomes/clean_data/multismash-results/testingMultismash/testing-w-2-SargMAGs/bigscape --mix --no_classify --include_singletons --clans-off --cutoffs 0.3 0.4 0.5 0.6 0.7
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2023-08-29T023324.378255.snakemake.log
```

[config_sarg.txt](https://github.com/zreitz/multismash/files/12462781/config_sarg.txt)

Thank you, Zach!!!!

**Comment by zreitz** [comment]
Ah of course, that won't work if you want BiG-SCAPE as well. Can you try `--use-conda` and just leave `antismash_conda:` blank? It should then use your current environment for antiSMASH.

**Comment by tarunaaggarwal** [comment]
Hi Zach! Happy to report that leaving the `antismash_conda:` blank works like a charm! Thank you for helping me get multismash up and running!

**Comment by zreitz** [comment]
No problem! Thanks for beta testing. I will mark this closed when I update the documentation.
