### ISSUE TITLE
error during antismash7 install - "ERROR: Could not build wheels for ..."

### ISSUE THREAD

**Issue by alpole23** [zreitz/multismash#6]
Hi zreitz,

To preface my issue, I am by no means a command line pro, and I only use the command line for bioinformatics tools as necessary for my research. My university has a HPC cluster that we use for our analyses, so all of the following is taking place on my individual user node.

I followed your "secret recipe for an antiSMASH 7.0 conda environment" installation using Miniconda3. Everything went smoothly up until the actual antismash install. I keep running into the error involving building wheels for biopython and MOODS-python.

![Capture](https://github.com/zreitz/multismash/assets/151235545/4b2f5f4e-6592-4369-a38e-e64234047e64)

I looked up this issue and found that…
 
The error "Failed building wheel for X" occurs for multiple reasons...
 

1. Not having the wheel package installed in the environment. 
I confirmed I am running Python 3.10.13 and the wheel package was included (pkgs/main/linux-64::wheel-0.41.2-py310h06a4308_0). I also tried with Python 3.9, 3.11, and 3.12 and received the same error.
 
2. Having installed packages that clash with the package we are trying to install.
Maybe? But I am not sure how I can troubleshoot this. I always start from a clean conda environment so I am not sure what could be conflicting.
 
3.  Having a Python version that isn't supported by the package we are trying to install.
AntiSHASH works with Python 3.9 and up so this is not the issue.

We are wanting to use multiSMASH on all enterobacterial genomes (~600 genomes). Any help would be greatly appreciated.

**Comment by zreitz** [comment]
Hello, thanks for trying out multiSMASH!

`error: command 'gcc' failed: No such file or directory`

Do you have GCC installed? Perhaps one of the solutions here will work: https://stackoverflow.com/questions/17972347/error-command-gcc-failed-no-such-file-or-directory

**Comment by alpole23** [comment]
Thanks for your suggestion. GCC is installed. 

![Capture](https://github.com/zreitz/multismash/assets/151235545/006c1cca-639f-41da-a8dd-f08a7f2c1726)

I have tried installing using python virtual environment running v3.10.1 but to no avail... getting the same "Could not build wheels..." error during antismash install. At this point, I do not know if the issue is a conda issue, an antismash version 7 issue, or a configuration issue on our end.

**Comment by zreitz** [comment]
I'm going to close this issue in favor of the [antiSMASH one](https://github.com/antismash/antismash/issues/674#issuecomment-1818039955), sorry I can't help more.
