### ISSUE TITLE
multismash tabulation fails when at least one antismash run fails

### ISSUE THREAD

**Issue by alpole23** [zreitz/multismash#9]
I am running multismash on about 500 genomes with the plan to expand to all genbank sequences. I noticed that the tabulation script fails when antismash fails to run on at least one genome.

the antismash error I am experiencing is:

> 11/12 10:07:40   CP091098.1: inconsistent exon ordering for features

which I am assuming has to do with an error in how the genome was submitted into the genbank database and nothing that antismash can resolve itself... and is not an issue that I am concerned with at this point.

However, in regards to the multismash tabulation feature, I was wondering if it is possible to force to run the tabulation on only the successful antismash outputs?

**Comment by zreitz** [comment]
Have you tried setting the configuration `antismash_accept_failure: True`?
https://github.com/zreitz/multismash#error-handling-what-happens-if-individual-antismash-jobs-fail

**Comment by alpole23** [comment]
Yes, I have tried setting `antismash_accept_failure: True` and the tabulation fails to run.

I also included a copy of the yaml configuration that I am using if that helps.

[antismash7_Erw._GenBank_all_fna.yaml.txt](https://github.com/zreitz/multismash/files/13652451/antismash7_Erw._GenBank_all_fna.yaml.txt)

**Comment by zreitz** [comment]
Thanks for catching this. I think the problem was a bad bash construct that somehow worked on my old machine. I've pushed a fix; can you pull and try again?

**Comment by alpole23** [comment]
Yes, works great now! Thanks for fixing this. 

P.S. multismash is a great tool so thank you for developing it.

**Comment by zreitz** [comment]
Thank you! I'm glad it's being used. Thanks for beta testing, please let me know if you encounter any other problems or see improvements to be made.

**Comment by alpole23** [comment]
Hi zreitz, I am having another problem with the tabulation that maybe you can help with. The antismash error that causing the tabulation to fail is different from the previous one above. I have included the portion of the snakemate log with the antismash error. It appears the genome sequence is corrupted in some way, which fails the antismash run... which then causes the tabulation to fail.

[multismash_error.txt](https://github.com/zreitz/multismash/files/13772763/multismash_error.txt)
